options:
  python-version:
    type: int
    default: 3
    description: THIS OPTION IS DEPRECATED AND HAS NO EFFECT
  triliovault-pkg-source:
    type: string
    default: "deb [trusted=yes] https://apt.fury.io/triliodata-4-0/ /"
    description: Repository address of triliovault packages
